Add Computable-reals library
coalton-lang/coalton pull request #1016
Opened 2023-10-12 00:22 UTC by Izaakwltn

This adds a computable-reals library, wrappers around functions from: https://github.com/stylewarning/computable-reals

2023-10-12 00:55 UTC, stylewarning requested changes
a few things to start

2023-10-12 00:55 UTC, stylewarning commented on library/reals/README.md
> +`EQ` and `Ord` have been implemented in order to fulfill the needs of the `Num` typeclass, though they are not exact. Their definitions are shaky because they can only be verified up to an arbitrary,
I wouldn't mention the Lisp variable name, and the Coalton function names need changing.

2023-10-12 00:55 UTC, stylewarning commented on library/reals/coalton-reals.lisp
> +  (define (set-comparison-threshold! k)
Return Unit.

2023-10-12 00:55 UTC, stylewarning commented on library/reals/coalton-reals.lisp
> +  (define (comparison-threshold) ;; radix point
stray comment

2023-10-12 00:55 UTC, stylewarning commented on library/reals/coalton-reals.lisp
> +      (/ 1 n))))
use /r with one argument

2023-10-12 00:55 UTC, stylewarning commented on library/reals/coalton-reals.lisp
> +        (cr:Expt-r x (cl:/ 1 n))))
(cl:/ n)

2023-10-12 00:55 UTC, stylewarning commented on library/reals/coalton-reals.lisp
> +        ((coalton-library/math/complex::%Complex a _) a)))
package name

2023-10-12 05:31 UTC, stylewarning approved these changes
nit: i think the creal functions should be lowercased, but it won't block the PR.

Since I only had nits, I can merge tomorrow, but you can make the tweaks before then if you want.

2023-10-12 05:31 UTC, stylewarning commented on library/reals/README.md
> +`EQ` and `Ord` have been implemented in order to fulfill the needs of the `Num` typeclass, though they are not exact. Their definitions are shaky because they can only be verified up to an arbitrary,
nit: `Eq` not `EQ`

2023-10-12 05:31 UTC, stylewarning commented on library/reals/coalton-reals.lisp
> +      (cond ((math:zero? diff-approxd)
nit: newline after cond

2023-10-12 05:31 UTC, stylewarning commented on library/reals/coalton-reals.lisp
> +    (define (Complex a b)
nit: lowercase `c` for the `complex` method

2023-10-12 05:44 UTC, eliaslfox commented
I'll look at this tomorrow.

2023-10-12 06:36 UTC, Izaakwltn commented
> nit: i think the creal functions should be lowercased, but it won't block the PR.
> 
> Since I only had nits, I can merge tomorrow, but you can make the tweaks before then if you want.

Nits picked

2023-10-16 23:14 UTC, eliaslfox approved these changes

2023-10-16 23:14 UTC, eliaslfox commented on coalton.asd
> +(asdf:defsystem #:coalton/library/reals
`#:coalton-library/computable-reals`

2023-10-16 23:14 UTC, eliaslfox commented on coalton.asd
> +  :pathname "library/reals"
`library/computable-reals`

2023-10-16 23:14 UTC, eliaslfox commented on library/reals/lisp-reals.lisp
> +(defgeneric into-creal (x)
Don't define generic functions to call from Coalton. Just call the implementation directly in the instance definition.

2023-10-19 00:39 UTC, merged