Benchmark sanitization and minor additions
coalton-lang/coalton pull request #1207
Opened 2024-08-12 19:07 UTC by Izaakwltn

Addressing issue #1204, this sanitizes the directory while we figure out how to replace `trivial-benchmarks`.
- Changes the benchmarks library to package-per-file
- Removes `trivial-benchmarks` as a dependency

This also adds two benchmarks from [the Benchmarks Game](https://benchmarksgame-team.pages.debian.net/benchmarksgame/index.html), with hopeful additions coming soon.

I think next steps (for future PR(s)) should include a simple Coalton benchmarking framework, ideally without external dependencies, and incorporation of benchmarks into CI.

2024-08-13 06:53 UTC, stylewarning requested changes
this PR is still a draft and needs a lot of preparation

2024-08-13 06:53 UTC, stylewarning commented on benchmarks/benchmarks-game/mandelbrot.lisp
> +(defpackage #:coalton/benchmarks/benchmarks-game/mandelbrot
we should write a comment on what this code is benchmarking. i don't mean documenting what mandelbrot is, but rather "this code benchmarks highly polymorphic complex numerics, and high order functions. the code is written in a relatively idiomatic functional style." or so

2024-08-13 06:53 UTC, stylewarning commented on benchmarks/benchmarks-game/mandelbrot.lisp
> +          (break :escape)
return should soon work when an open pr is merged within 24h

2024-08-13 06:53 UTC, stylewarning commented on benchmarks/benchmarks-game/mandelbrot.lisp
> +      (lisp Unit (bi)
delete

2024-08-13 06:53 UTC, stylewarning commented on benchmarks/benchmarks-game/mandelbrot.lisp
> +          )
fix parens

2024-08-13 06:53 UTC, stylewarning commented on benchmarks/benchmarks-game/too-simple.lisp
> +            (let sum = (cell:new 0.0d0))
lift the fn out into its own function

2024-08-13 06:53 UTC, stylewarning commented on benchmarks/benchmarks-game/too-simple.lisp
> +            (let ((declare run (Double-Float -> Double-Float -> Double-Float -> Double-Float))
same

2024-08-13 06:53 UTC, stylewarning commented on benchmarks/big-float.lisp
> +;;(cl:in-package #:coalton-benchmarks)
dead code

2024-08-13 06:53 UTC, stylewarning commented on benchmarks/big-float.lisp
> +#+ig
figure out what to do with these

2024-08-13 06:53 UTC, stylewarning commented on benchmarks/fibonacci.lisp
> +#+ig (define-benchmark recursive-fib ()
figure out what to do here.

2024-08-13 07:05 UTC, Izaakwltn commented
Whoops, I thought I marked it as a draft

2024-11-07 18:33 UTC, Izaakwltn commented
Closing this as it's superseded by #1286 

The additional benchmarks defined in this PR will be added to a new PR after #1286 merges.

2024-11-07 18:33 UTC, closed without merging