source:location generic function
coalton-lang/coalton pull request #1223
Opened 2024-09-03 19:52 UTC by jbouwman

Make location generic across parser and typechecker nodes using :include to provide slot definitions.

This change is similar to the introduction of #'source:docstring in #1220

2024-09-03 20:32 UTC, Izaakwltn approved these changes
Seems like a reasonable (and more readable) change

2024-09-03 22:02 UTC, stylewarning requested changes
My instinct is that using :include will lead to brittle design. What do we do when we want everybody to have more common slots? Behaviorally the subtype relationship also doesn't make much logical sense (it's not really an "is a" relationship).

Can we do this without using "include"? I feel all we are saving is typing.

2024-09-03 22:05 UTC, stylewarning commented
I should add that if this were a class, I would find it less objectionable, but I would prefer not to turn `node` types into classes since the compiler is already difficult to debug.

2024-09-03 22:38 UTC, jbouwman commented
Yes, it's easy to keep :include out of this and in retrospect preferable. Revising.

2024-09-03 22:49 UTC, stylewarning commented
> Yes, it's easy to keep :include out of this and in retrospect preferable. Revising.

One possibility is to create more superclasses. Maybe include a location on NODE, maybe another on something like TOPLEVEL-FORM (which we'd have to make), etc. That way we have sensible and organized classes whilst not having a lot of duplication.

2024-09-12 21:11 UTC, stylewarning requested changes
- rename coalton-object
- split tc-error into a location case and locatable case

2024-09-12 21:11 UTC, stylewarning commented on src/entry.lisp
>                           "Amqbiguous accessor"
typo

2024-09-13 02:58 UTC, stylewarning approved these changes

2024-09-13 03:01 UTC, merged