Adding dependency information to README
coalton-lang/coalton pull request #1240
Opened 2024-09-12 21:02 UTC by Izaakwltn

This adds information about two current dependencies, `FSET` and `MISC-EXTENSIONS`, to the README.

2024-09-12 22:41 UTC, jbouwman approved these changes

2024-09-13 02:10 UTC, stylewarning requested changes

2024-09-13 02:10 UTC, stylewarning commented on README.md
> +**Add dependencies** While Quicklisp will automatically ensure almost all of Coalton's dependencies, you will need to manually clone [FSET](https://github.com/slburson/fset/) and [MISC-EXTENSIONS](ht
Capitalization: ASDF and Quicklisp

2024-09-16 18:29 UTC, Izaakwltn commented on README.md
> +**Add dependencies** While Quicklisp will automatically ensure almost all of Coalton's dependencies, you will need to manually clone [FSET](https://github.com/slburson/fset/) and [MISC-EXTENSIONS](ht
Fixed

2024-09-20 20:46 UTC, Izaakwltn commented
Should this also mention the dependency on GNU-MPFR in order to run tests?

2024-09-20 22:56 UTC, stylewarning commented
> Should this also mention the dependency on GNU-MPFR in order to run tests?

probably

2024-09-23 21:03 UTC, stylewarning approved these changes
Solid!

2024-09-23 21:03 UTC, merged