More library additions
coalton-lang/coalton pull request #1243
Opened 2024-09-13 21:53 UTC by YarinHeffes

Macros: `unwrap-as` and `try-as`
Additional standard library functionality.

2024-09-15 03:31 UTC, amorphedstar commented on library/ord-map.lisp
> +Construct a Map containing only those mapping sof `a` and `b` which do not associate keys `==' keys in the other."
```suggestion
Construct a Map containing only those mappings of `a` and `b` which do not associate keys `==' keys in the other."
```

2024-09-15 03:35 UTC, amorphedstar commented on library/ord-tree.lisp
> +    "Does `tre` containan element `=='`to `elt`."
```suggestion
    "Does `tre` contain an element `==` to `elt`."
```

2024-10-02 21:52 UTC, Izaakwltn requested changes
These changes look good-

I'm ready to approve it with
1. An adjusted commit history (squash merges, reverts, wip commits)
2. add some tests for new functions, especially in `ord-tree` and `ord-map`, potentially for  `try-as` and `unwrap-as` as well

2024-10-02 21:52 UTC, Izaakwltn commented on library/string.lisp
> +        #+ign(cl:prin1-to-string z))))
remove ignores

2025-01-13 17:04 UTC, stylewarning commented
I think we'll want to break this PR up into a few logical chunks. Large sweeping library additions of unrelated functionality are usually too bikesheddable and contentious to review.

2025-07-31 23:50 UTC, YarinHeffes commented
I don't think there's anything important left here that won't be covered by some collections library changes soon.

2025-07-31 23:50 UTC, closed without merging