Split benchmark packages
coalton-lang/coalton pull request #1276
Opened 2024-10-02 09:49 UTC by shirok

As we have more benchmarks, it is more convenient to allow running not only the entire benchmarks, but the specific group of benchmarks of concern. Trivial-benchmarks treats each benchmark package as a group. This patch establishes a convention to create multiple benchmark packages.

These commits try to keep changes small, for easier transition.

2024-10-02 10:25 UTC, stylewarning requested changes

2024-10-02 10:25 UTC, stylewarning commented on benchmarks/package.lisp
> +        (native-package (intern (format nil "BENCHMARK-~S/NATIVE" name) 'keyword)))
Can these be `COALTON-BENCHMARK/...`? It's a little wordier, but worth it.

Maybe also add a default package local nickname "NATIVE" for the native package. That way the actual benchmarks can always refer to `native:...`.

In general I don't like symbol generating macros, but for this limited use case I think it's fine.

2024-10-02 10:31 UTC, Izaakwltn commented
Just a quick note:  `trivial-benchmarks` on quicklisp is out of date, and the API has changed significantly (there are no longer benchmark packages). 

Issue #1204

2024-10-02 20:42 UTC, shirok commented
Any recommendation for alternative benchmarking package?
I have several benchmarks depending on this change, so I'd like to solidify the foundation of benchmarking now.

2024-10-03 03:12 UTC, Izaakwltn commented
Are your benchmarks using mostly Coalton or would you ideally like equal support for Common Lisp benchmarks?

2024-10-03 04:42 UTC, shirok commented
I aim at specific use patterns that are expected to be optimized by the Coalton compiler, but it includes Common Lisp counterpart as base cases, so the framework needs to measure both cases.

2024-10-03 07:12 UTC, Izaakwltn commented
I wrote an initial draft of a potential implementation in Coalton, does this look like it might be able to support what you want in your benchmarks?
#1286

2024-10-03 07:35 UTC, shirok commented
Yes. At this moment, the essential feature is to have a standard way to define benchmarks and run them per-package.  I can call plain-CL version of benchmark code from Coalton anyway. 

If #1286 will be merged soon, I'll adapt my other benchmarks to it.

2024-10-03 11:10 UTC, shirok commented
Wait, the commit has unintended changes... let me check.

2025-05-14 23:53 UTC, shirok commented
Superseded by https://github.com/coalton-lang/coalton/pull/1455

2025-05-14 23:53 UTC, closed without merging