Change `Quantization` from type to struct; doc upgrade
coalton-lang/coalton pull request #1312
Opened 2024-10-15 18:52 UTC by Izaakwltn

2024-10-15 19:08 UTC, Izaakwltn commented
Fixes #1308

2024-10-15 19:09 UTC, jbouwman approved these changes
useful clarification

2024-10-15 21:34 UTC, Izaakwltn commented on library/math/real.lisp
> +    (floor       "The greatest integer less than or equal to a particular value."
@stylewarning are these reasonable field names?

2024-10-16 18:17 UTC, stylewarning requested changes
looks good, just doc tweaks

2024-10-16 18:17 UTC, stylewarning commented on library/math/real.lisp
> +    (floor-rem   "The remainder of this as a value of type `:a`."
don't say "of this", try to be self-contained. "The remainder of the floor operation." or something

2024-10-16 22:37 UTC, stylewarning approved these changes

2024-10-16 22:37 UTC, merged