Use bare abstractions for methods
coalton-lang/coalton pull request #485
Opened 2022-04-05 01:40 UTC by eliaslfox

2022-04-05 01:47 UTC, stylewarning commented
Can you describe more what this is and what it means?

2022-04-05 02:36 UTC, eliaslfox commented
Normal abstractions when passed as arguments become `(F2 (lambda (a b) ...))`. Bare abstractions skip the `F2`. This lets us skip the currying machinery on method calls. 

The previous backend did the same thing.

2022-04-06 04:15 UTC, stylewarning requested changes

2022-04-06 04:15 UTC, stylewarning commented on src/codegen/ast.lisp
> +            (:constructor node-bare-abstraction (type vars subexpr)))
can you add a doc string to abstraction and bare-abstraction (and maybe others too)?

2022-04-07 20:39 UTC, stylewarning requested changes
just a little more docs sprucing up

2022-04-07 20:39 UTC, stylewarning commented on src/codegen/ast.lisp
> +  "Lamba literals (fn (x) x)"
lambda

2022-04-07 20:39 UTC, stylewarning commented on src/codegen/ast.lisp
> +  "Lambda literals which do not need be wrapped in function-entries. This
can you add a "because ..."? Just a little more insight as to why they don't need to be wrapped.

2022-04-07 20:39 UTC, stylewarning commented on src/codegen/ast.lisp
> +  "Introduction of local bindings (let ((x 2)) (+ x x))"
local mutually-recursive

2022-04-07 20:39 UTC, stylewarning commented on src/codegen/ast.lisp
> +  "A Branch of a match statement"
lowercase b

2022-04-07 20:39 UTC, stylewarning commented on src/codegen/ast.lisp
> +  "A match statement"
A pattern matching construct. Uses MATCH-BRANCH to represent branches.

2022-04-07 20:39 UTC, stylewarning commented on src/codegen/ast.lisp
> +  "A return statement"
, used for early returns in a function.

2022-04-07 20:51 UTC, stylewarning approved these changes

2022-04-07 20:54 UTC, stylewarning commented
@eliaslfox I changed the repository settings to require `test` now instead of `build`.

2022-04-07 20:55 UTC, merged