Define coalton macros while in the coalton package
coalton-lang/coalton pull request #488
Opened 2022-04-06 21:05 UTC by eliaslfox

This avoid package lock violations when reloading the asdf system.

2022-04-06 23:49 UTC, stylewarning requested changes

2022-04-06 23:49 UTC, stylewarning commented on src/coalton.lisp
> +(in-package #:coalton)
I don't understand why you're not just in-package coalton-impl and qualifying them coalton symbols as done already

2022-04-06 23:49 UTC, stylewarning commented on src/debug.lisp
> -(defun print-value-db (&optional package)
same here

this looks very bizarre; there must be a better way than to use this SBCL-specific extension

2022-04-07 00:17 UTC, stylewarning reviewed
I'm happy to approve this, but what do you think about making an explicit files "lock-package" and "unlock-package" both with :if-feature sb-package-locks?

2022-04-07 00:23 UTC, eliaslfox commented
I like that

2022-04-07 01:08 UTC, stylewarning approved these changes

2022-04-07 01:08 UTC, merged