Add Fractional class
coalton-lang/coalton pull request #510
Opened 2022-05-10 19:59 UTC by eliaslfox

2022-05-10 20:51 UTC, stylewarning commented
I don't actually see the definition of Fractional in the diff.

2022-05-10 20:52 UTC, eliaslfox commented on library/arith.lisp
> +(coalton-toplevel
@stylewarning  It's here

2022-05-11 18:18 UTC, stylewarning requested changes
I'm open to not making this change, but as a math-code writer, I prefer things to be more specific.

2022-05-24 22:37 UTC, eliaslfox commented
Closing in favor of the type class hierarchy in #533

2022-05-24 22:37 UTC, closed without merging