Add type annotations to struct definitions
coalton-lang/coalton pull request #739
Opened 2022-09-20 23:00 UTC by colescott

Resolves #708

2022-09-20 23:01 UTC, eliaslfox approved these changes

2022-09-20 23:24 UTC, stylewarning requested changes
CI is ❌

2022-09-20 23:24 UTC, stylewarning commented on src/typechecker/lisp-type.lisp
>    (:documentation "Returns the corresponding lisp type for the type of the given node")
can you document this option?

2022-09-20 23:24 UTC, stylewarning commented on src/typechecker/lisp-type.lisp
> +(defgeneric lisp-type (ty env &key use-function-entries)
you might make the generic function `%lisp-type` or `lisp-type-gf` and not have the annoying KW arg, then define

```
(defun lisp-type (ty env &key use-fu)
  (%lisp-type ty env use-fn))
```

Not required, but would make the methods nicer without having to repeat yourself with the optional values.

2022-09-21 17:52 UTC, stylewarning approved these changes

2022-09-21 17:52 UTC, merged