Doc on how to write a Coalton test suite
coalton-lang/coalton pull request #962
Opened 2023-07-07 01:22 UTC by Izaakwltn

I wrote a simple guide to writing a test suite for Coalton.

2023-07-07 04:48 UTC, stylewarning requested changes

2023-07-07 04:48 UTC, stylewarning commented on docs/implementing-tests.md
> +### First you will define the Fiasco test package for your project:
This is a little bikesheddy but could you not put verbiage like this in section headings (here and elsewhere), and instead make it paragraph content? Maybe something like:

```
### Step 1: Define a package

First you will define ...
```

2023-07-13 17:03 UTC, macrologist commented on docs/implementing-tests.md
> +Within the Coalton test-package, initialize Fiasco compatibiltiy by calling `#'coalton-fiasco-init` with your Fiasco test-package.
The hypen isn't needed

2023-07-13 17:12 UTC, Izaakwltn commented on docs/implementing-tests.md
> +Within the Coalton test-package, initialize Fiasco compatibiltiy by calling `#'coalton-fiasco-init` with your Fiasco test-package.
Sounds good, changed throughout

2023-07-18 18:27 UTC, eliaslfox commented
Closing this in favor of #874 which is more comprehensive.

2023-07-18 18:27 UTC, closed without merging