Added seq get-unsafe and put-unsafe, corresponding tests
coalton-lang/coalton pull request #979
Opened 2023-08-04 18:44 UTC by Izaakwltn

Added unsafe options for seq:get and seq:put, with verbose errors.

2023-08-04 18:56 UTC, stylewarning requested changes

2023-08-04 18:56 UTC, stylewarning commented on library/seq.lisp
> +    #:coalton
nit: not right indentation

2023-08-04 18:56 UTC, stylewarning commented on library/seq.lisp
> +      (_None (error (let ((l (math:1- (size seq))))
`((None) ...)`

2023-08-04 18:56 UTC, stylewarning commented on library/seq.lisp
> +      (_None (error (let ((l (math:1- (size seq))))
`((None) ...)`

2023-08-04 20:19 UTC, stylewarning approved these changes

2023-08-04 20:19 UTC, stylewarning commented on library/seq.lisp
> +                   (lisp String (l idx)
style nit: indentation

2023-08-04 20:19 UTC, stylewarning commented on library/seq.lisp
> +                   (lisp String (l idx)
style nit: indentation

2023-08-04 23:04 UTC, Izaakwltn commented
@macrologist suggested reworking `get-unsafe` and `put-unsafe` as altered copies of `get` and `put` so that they're hopefully faster. 

@stylewarning Do these look like better than the existing PR?
```
  (define (get-unsafe seq idx)
    "Get the member of `seq` at index `idx`, or `None` if `idx` >= `(size seq)`"
    (match seq
      ((LeafArray leaves)
       (vector:index-unsafe idx leaves))
      
      ((RelaxedNode _ fss cst sts)
       (unwrap
         (do
          (let guess = (math:div idx fss))
          ((Tuple subtree-idx offset) <- (cst-search guess cst idx))
           (subtree <- (vector:index subtree-idx sts))
           (get subtree (- idx offset)))))))
```
```
  (define (put-unsafe seq idx a)
    "If `idx` is less than `(size seq)`, Return a new `seq` whose `idx` position
contains `a`."
    (match seq
      ((LeafArray leaves)
       (if (<= (vector:length leaves) idx)
           (error (let ((l (math:1- (size seq))))
                    (lisp String (l idx)
                      (cl:format cl:nil "Invalid index ~a for Seq with max index ~a." idx l))))
           (let ((newleaves (vector:copy leaves)))
             (vector:set! idx a newleaves)
             (LeafArray newleaves))))

      ((RelaxedNode h fss cst sts)
       (unwrap
        (do
         (let guess = (math:div idx fss))
         ((Tuple subtree-idx offset) <- (cst-search guess cst idx))
          (subtree <- (vector:index subtree-idx sts))
          (new-subtree <- (put subtree (- idx offset) a))
          (let ((newsts (vector:copy sts)))
            (vector:set! subtree-idx new-subtree newsts)
            (pure (RelaxedNode h fss cst newsts))))))))
```

2023-08-05 00:08 UTC, macrologist commented
These are still just calling `get` and `put` respectively. In your definition for the unsafe get, for example, it's just calling the safe `get` at every step except in the special case that you start with a leaf node. So rather than wrapping the second match case in an `unwrap` - instead get in there and eliminate all the dependence on the `Maybe` monad, using `vector:index-unsafe` whenever you can.

2023-10-11 20:29 UTC, stylewarning commented
Closing; can be opened as a new PR with a more sharp-edge approach.

2023-10-11 20:29 UTC, closed without merging